import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ModalProvider from './providers/ModalProvider'
import QueryProvider from './providers/QueryProvider'
import ToasterProvider from './providers/ToasterProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pancake',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
        <ToasterProvider/>
        <Navbar/>
        <ModalProvider/>
        <div className='container max-w-7xl mx-auto h-full pt-12'>
        {children}
        </div>
        </QueryProvider>
      </body>
    </html>
  )
}
